### ISSUE TITLE
Constantly asking to update to 2.0.2

### ISSUE THREAD

**Issue by merreltc** [aluxian/Messenger-for-Desktop#1009]
* Operating system: Ubuntu 16.04
* Messenger for Desktop version: 2.0.1
It seems like I am doing this but I keep getting the request?

**Comment by dansk** [comment]
Same thing here, it's really obnoxious.

OS: Linux Mint 18
Messenger for Desktop version: 2.0.1

**Comment by novotnej** [comment]
Not only that, but when I actually try to update, it downloads the same version and keeps asking...

**Comment by dbosman** [comment]
I got the same issue as merreltc and novotnej.
OS: Ubuntu 16.04

**Comment by Sytten** [comment]
Is it still relevant in the V2.0.4?

**Comment by novotnej** [comment]
Mate what the hell are you doing there? I just tried to download the new Deb 64 version from [https://messengerfordesktop.com/#download](https://messengerfordesktop.com/#download) and it downloaded version 1.4.3!

and also it might be a good idea to have the current version number next to the downloads so that if we have this update error again, we can check if it's worth downloading and reinstalling..

**Comment by novotnej** [comment]
in any case I just installed the new version from releases and the issue is gone (for now). but update the website or it will appear again when you have a new version available!

**Comment by aluxian** [comment]
Website is fixed. Also, since v2.0.4 is released v2.0.2 shouldn't be picked up anymore.
