### ISSUE TITLE
Don't know how to install.

### ISSUE THREAD

**Issue by Dark-Witcher** [aluxian/Messenger-for-Desktop#1151]
* Operating system: Solus 1.2.1 Budgie Desktop 64-bit
* Messenger for Desktop version: none

So any idea how to install it on Solus OS? I love the app, I just change from Mint 18 to Solus and I want to continue using it! But I have no idea how to install it. Any advice would be much appreciated. (I don't want to hear anything like: "Get back to Debian/Ubuntu/Mint!" or "Pleb, use Arch!")

Thanks in advance!

**Comment by Sytten** [comment]
Since its seems to use a custom package manager and is not a fork from any major distribution, my best guess would be to try to compile it. It pretty easy to do and you can manually move the generated files after somewhere else. Even better, you could write the necessary code to package it for your distro and publish it where other could find it.

**Comment by Dark-Witcher** [comment]
Thanks, Sytten.
Can you give me like a short how-to guide :D because I have no idea how to compile it.

**Comment by Sytten** [comment]
I have stopped working on the project since it switched to electron (I only maintain v1 with nwjs), but the readme seems well explained:
https://github.com/Aluxian/Messenger-for-Desktop#for-developers
You should get used to build your own stuff if you use funky distributions...

**Comment by Dark-Witcher** [comment]
Thanks again, Sytten. 
And yeah, I know that I have to build most stuff myself. Spend the last 4 days trying to build apache2 :D in the end turn out that there is a package build named httpd :D
