### ISSUE TITLE
Javascript error in the main process

### ISSUE THREAD

**Issue by sant1ago** [aluxian/Messenger-for-Desktop#1170]
* Operating system: OSX 10.11.6
* Messenger for Desktop version: 2.0.4

When launching Messenger I get the following error:
<img width="416" alt="screen shot 2017-01-25 at 9 29 30 am" src="https://cloud.githubusercontent.com/assets/13040407/22296819/fad6b5cc-e2e0-11e6-8635-3b6042fa8c8d.png">

**Comment by tigereyes7088** [comment]
I installed the update as suggested but I am still getting that Java error.

**Comment by Sytten** [comment]
Yes @aluxian is working on it

**Comment by Zorakie** [comment]
Hi, any progress in this? When will be the new bug-fixing release? Messenger is totaly unusable like this and yes, this is the best project ... no other projects suits my (our) needs :/

**Comment by JakesCode** [comment]
Yeah, I'm stuck with the old version which can't play audio or video files. It's a shame because, as @Zorakie says, it's the best app for Desktop Messenger at the moment, and no others are on par.

**Comment by aluxian** [comment]
Please try v2.0.5:

https://github.com/aluxian/Messenger-for-Desktop/releases/tag/v2.0.5

**Comment by tigereyes7088** [comment]
Thank you so much!! [😤]

________________________________

**Comment by Zorakie** [comment]
Great one, @aluxian , you are the best! 

BTW was you thinking about releasing it for example to MS store, or something like this? For now, there are really shitty apps ... official FB very often won't you log in, someone has issues with registration, some other assets like smileys are bad as I heard and many many many other things. Also other "unofficial wrappers" are probably not good, at least I have not found better than your app there. (mostly just because a possibility of running it in tray, and notifications). 

Just a suggestion to get more "fanbase" and maybe start some small donation possibility as I think this is a very good project and sould be maintained and kept alive (and everybody knows, that this goes much worse, if the author is just slave of his own work and has nothing from it )  ;)


Anyway, thanks again :)

**Comment by aluxian** [comment]
@Zorakie thanks for the suggestion
