### ISSUE TITLE
Option to prevent application badge flashing

### ISSUE THREAD

**Issue by ivancuric** [Aluxian/Messenger-for-Desktop#123]
Could an option be implemented to prevent the notification badge flashing in the OSX dock?

**Comment by Aluxian** [comment]
That's unintended behaviour. I don't really know how to stop it from blinking, I've tried before.

1. Please make sure you're running the latest version
2. Tell me what the title of the window is when you don't have any unread messages/notifications. For me, it's just `Messenger`.
3. When I receive a new message, my window's title changes to `(1) Messenger` which means I have 1 unread message. What does yours say?
4. If I don't read the message, the window title keeps alternating between `(1) Messenger` and `XX messaged you`. What does yours say?

That's what causes the blinking. For me it doesn't happen, though, that's why I can't solve the bug. Let me know whether you've seen any other window titles. Also, knowing the language you use on Facebook might help.

**Comment by TravelMedMike** [comment]
First, I have mine set as "Run as Menu Bar App" 

1. Latest Version: Version 1.4.3 (1.4.3)
2. Title of Window When No Unread Messages/Notifications: Messenger
3. Title of Window with new message/notification: Messenger 
4. If I don't read the message: Messenger

When it's in Menu Bar App icon mode - (and if Messenger is kept in the dock) - It stays lit, but no number changes on the Dock icon. 
If the Menu Bar icon mode is off, and a new message comes on, all of the above is the same except that a red number 1 shows up on the Dock icon, regardless of how many new messages come in. 

So far I cannot replicate the bug, even though I saw it earlier this morning on start up.

Edit: After Start Up - 
Could not replicate the "blinking menu bar icon bug" 

However - in a separate and already mentioned minor issue - 

When a new message is received, sound notification works.
But - Cannot see the Notification Banner in the top right appear across the screen momentarily for more new messages until you click on a message inside the App window. After that, the notification banner works for further messages. 
The notifications however do not "stay" in the Notification Center and are thus not "reply-able" from within the notification center... 
To me it does not matter though, because if the menu bar icon is lit on, then you have an unread message.. 

Please excuse any errors in syntax or jargon, as this is my first bug report on github and I do not work in this field :)

Other than that, this app still seems to be better than all the other Facebook Messenger desktop apps out there for OS X. 


I'm using 10.10.3 OS X

Regards, Mike

**Comment by jelen07** [comment]
I have some issue on Macbook Pro, Air is ok.
https://youtu.be/k_EDHXzdIx8
