### ISSUE TITLE
installing for macOS from messengerfordesktop.com comes with bloatware

### ISSUE THREAD

**Issue by cdbattags** [aluxian/Messenger-for-Desktop#1254]
* Operating system: macOS
* Messenger for Desktop version: 2.0.9-stable

This is just plain ridiculous... What installer is being used?

**Comment by Shalmezad** [comment]
On the main github page:
`Bring messenger.com to your OS X, Windows or Linux desktop. https://messengerfordesktop.org`

Looking at gitter:
```
@Sytten
Also the real domain is messengerfordesktop.org now
The com is trash
The com stays since we don't own it anymore
```

You grabbed from the wrong website, which is understandable since it's the top result in google. There's nothing the developers can do because they don't own the domain.
