### ISSUE TITLE
Possible Update Check on Portable Startup Connecting with MessengerforDesktop dot com instead of .ORG

### ISSUE THREAD

**Issue by sheldonhull** [aluxian/Messenger-for-Desktop#1259]
* Operating system: Windows 10
* Messenger for Desktop version:  2.0.9

First startup of portable app initiated connection: 
```
Domain: updates.messengerfordesktop.com
IP: 104.24.108.166 - California 
```
Since messengerfordesktop.org is supposed to be the correct service, with messengerfordesktop dot com being the adware/spyware hijacking that was experienced, can you explain why that's still listing messengerfordesktop.com  in the connection?

**Comment by sheldonhull** [comment]
I did a search through the repo, and I see src/package json still pointing to messengerfordesktop.com, and several other places referenced. Is this correct as I understood it should be .ORG now?

**Comment by sheldonhull** [comment]
I'm no longer running due to this. To many issues with possible privacy or spyware. This is an open source project but by default captures some metrics for the original "company", so I'm not going to keep considering this truly as a community based open source tool. Too risky. I sure hope for more clarity on this soon, or might just have to eventually fork and modify if I can get the time.

**Comment by aluxian** [comment]
There are no privacy or spyware threats. messengerfordesktop.com has installer ads, but other than that, both websites are the same.

There's only one updates server (mine, only I have access to it) and that's updates.messengerfordesktop.com.

The CI scripts and logs are public: when I push to brach `deploy`, the CIs build the app and then upload it to GitHub — that's all, and that's automatic and transparent. The [updates server is also open source](https://github.com/aluxian/squirrel-updates-server) and is simply a node.js server that redirects to GitHub releases, but of course since only I control it, you can't say it's fully trusted / transparent.

If you require a higher level of privacy and security then I recommend that you fork the app, remove every connection to my servers (i.e. analytics and updates), and build it yourself. For personal use, you don't need to sign it or any hassles that the CIs do.
