### ISSUE TITLE
[Windows] Shortcut appears twice in the apps view (Win8.1)

### ISSUE THREAD

**Issue by jkdel** [Aluxian/Messenger-for-Desktop#189]
Shortcut appears twice in the apps view (Win8.1) (BTW same bug for inofficial WhatsApp)
![a](https://cloud.githubusercontent.com/assets/3051086/8798827/93e3d948-2fa5-11e5-8156-d3c04582832a.png)

**Comment by devilirium** [comment]
I juse checked it, and it seems like the installer script creates a shortcut at `"$SMPROGRAMS\Messenger.lnk"`. This points here: `<WINDOWS>:\ProgramData\Microsoft\Windows\Start Menu\Programs\Messenger.lnk`

The path of the 2 shortcuts are:
```<WINDOWS>:\Users\<USERNAME>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
<WINDOWS>:\ProgramData\Microsoft\Windows\Start Menu\Programs```

The first one probably gets created automatically. I'll test it later today.

**Comment by Aluxian** [comment]
One shortcut is created in install, and another is created each time the app is
launched for Windows 8 notifications to work (weird, I know, that's what it says
in nwjs docs).

--

Alexandru Rosianu
Web & Android Developer
aluxian.com | startersquad.com On Fri, Jul 24, 2015 at 3:39 pm, Adam Tajti < notifications@github.com [notifications@github.com] > wrote:
I juse checked it, and it seems like the installer script creates a shortcut at "$SMPROGRAMS\Messenger.lnk" . This points here: <WINDOWS>:\ProgramData\Microsoft\Windows\Start Menu\Programs\Messenger.lnk

The path of the 2 shortcuts are:
<WINDOWS>:\Users\<USERNAME>\AppData\Roaming\Microsoft\Windows\Start
Menu\Programs
<WINDOWS>:\ProgramData\Microsoft\Windows\Start Menu\Programs

The first one probably gets created automatically. I'll test it later today.

—
Reply to this email directly or view it on GitHub
[https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/189#issuecomment-124507173] .[https://github.com/notifications/beacon/ABWmdg4pwsfNhcGj7dBWHprmIetXcaERks5ogimWgaJpZM4Fcpj3.gif]

**Comment by devilirium** [comment]
Indeed. I just observed that behaviour. Since both of the shortcut shows up everywhere, I'll just modify the installer scripts shortcut location to the one that you use in the source. I've also just modified the gulp script, since the ./dist folder creation was missing from the win32 task :)

**Comment by Aluxian** [comment]
Thanks! :)

Btw if it was missing, then most probably it wasn't required.

--

Alexandru Rosianu
Web & Android Developer
aluxian.com | startersquad.com On Fri, Jul 24, 2015 at 4:04 pm, Adam Tajti < notifications@github.com [notifications@github.com] > wrote:
Indeed. I just observed that behaviour. Since both of the shortcut shows up
everywhere, I'll just modify the installer scripts shortcut location to the one
that you use in the source. I've also just modified the gulp script, since the
./dist folder creation was missing from the win32 task :)

—
Reply to this email directly or view it on GitHub
[https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/189#issuecomment-124513583] .[https://github.com/notifications/beacon/ABWmdv21SOwnOB5k7Xzxe7yJbST8Uz-0ks5ogi9ggaJpZM4Fcpj3.gif]

**Comment by devilirium** [comment]
We can close this down after the merge. :)
It was required for me, so I included it.

Keep up the good work -

**Comment by Sytten** [comment]
I need to do some testing too see if its till relevant to the current code and I will include it in a next beta release for sure.
Thanks
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458 for more information about the beta.
