### ISSUE TITLE
Windows Design Improving

### ISSUE THREAD

**Issue by HassanAzzam** [Aluxian/Messenger-for-Desktop#221]
Good work, but I have a suggestion.
Why don't you make window bar and taskbar icon be like this?
![screenshot 29](https://cloud.githubusercontent.com/assets/9885144/9340242/ef644046-45ee-11e5-8ca8-03134dd37bef.png)

also the system tray icon, I think it will be good in white and when you have a notification, it turns into blue.
![screenshot 30](https://cloud.githubusercontent.com/assets/9885144/9340290/2519b964-45ef-11e5-8efc-6118a0816a6e.png)

thanks :)

**Comment by harchus** [comment]
I would like to see this happening. ♥

**Comment by Sytten** [comment]
With the current framework we can't make that title bar, but I like your idea for the tray icon.
Please try the new beta I made.
More information here: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458

**Comment by strandedPL** [comment]
Hey! Any updates on that try icon? It looks really bad on Windows 10:

http://i.imgur.com/MjozcUz.png

I can set you up with all the sizes of that official icon that you need, for some reason Windows 10 is still using the 16px icon for the taskbar icons. It's retarded, but I guess it could be fixed by simply adding the 16px icon.

The icon looks good at 125% DPI though!
http://i.imgur.com/1HwQ5Kk.png

**Comment by Sytten** [comment]
Well I'm waiting on the main dev to see when he is going to move to MDF 2 (based on electron).
It annoys me to work on code that is going to be thrown away in a month or two... 
(Also exams' weeks)

**Comment by strandedPL** [comment]
OK that makes sense, if it's going to be done from scratch don't waste your time on the stupid icon now. Good luck on your exams!
