### ISSUE TITLE
Window title on Gnome 3.16 is "Unknown"

### ISSUE THREAD

**Issue by cadecairos** [Aluxian/Messenger-for-Desktop#228]
App works beautifully, but the title shows up as "Unknown"

using Gnome 3.16.3 on Linux 4.1.6

**Comment by jackwilsdon** [comment]
Looks like this is an open issue with NW.js itself: nwjs/nw.js#3266

**Comment by Hori873** [comment]
It's fixed if you manually set a WM_CLASS using xprop... but you have to do that every time you open this application. This also fixes the icon issue if you use a custom icon theme.

**Comment by DoctorJellyface** [comment]
Yep, can confirm, still an issue on 3.18, would be nice to have at least a work-around.

**Comment by Hori873** [comment]
As a workaround you can create a wrapper script that launches this app and imediately after it launches xdotool and changes it's WM_CLASS to the one you set in this app's .desktop file in /usr/share/applications
You will have to use that script in order to luanch this app from now on, so it might be a good idea to put it in /usr/bin and change the .desktop file's Exec line

**Comment by Airblader** [comment]
Note that a wrapper script still violates the specification because the client is required to set the property before mapping the window.

**Comment by Hori873** [comment]
I agree. A wrapper script is by no means a solution, just a(n ugly) workaround, as I mentioned before. It would be really nice if the author could fix this issue in a proper way. I don't know how hard it would be since I don't really know Node.js but I do know that many Electron-based apps suffer from this same issue. Also as far as I know this problem only exists on Linux because WM_CLASS is an X Window property.
However, Whatsie dosen't seem to have this problem, so I assume that the author did indeed find a solution.

**Comment by Sytten** [comment]
Hi!
I invite you to try the new beta. I added a WM_CLASS (as far as I remember) and I personally never had this problem.
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458 for more information.
I will let this issue open a bit more to see if your problem is resolved.
