### ISSUE TITLE
[REQ] Different notification sounds

### ISSUE THREAD

**Issue by TheHaso** [Aluxian/Messenger-for-Desktop#29]
Hi

it would be great if you added some different notification sounds to choose from. The standar messenger "pling" is quite annoying sometimes. 

Heres KaprainG's mediapack. A lot of notification sounds from different phones. If its relevant.
http://forum.xda-developers.com/showthread.php?t=2723832

**Comment by Aluxian** [comment]
Actually, you just have me an idea! Ohh thank you!

I can't change the default sound because it's controlled by messenger.com. But what I can do, is disable the default one and play some by myself. This will also properly fix #26.

I will implement this based on the popularity of the other feature requests.

**Comment by faizaanceg** [comment]
+1 for this!

**Comment by wir3k** [comment]
+1 for this one !!

**Comment by TheHaso** [comment]
@Aluxian so, this never became a thing then. sad.
