### ISSUE TITLE
Right-click issues

### ISSUE THREAD

**Issue by aanrudolph2** [Aluxian/Messenger-for-Desktop#385]
It appears that Messenger has its own JavaScript handler(s) for right-clicking. Unfortunately, when I right-click in the app, both the native menu appears AND the HTML DOM menu appears (in the webpage). Perhaps the native right-click should check for DOM events before firing (or disable it entirely in the main pane?)
![bugreport_1](https://cloud.githubusercontent.com/assets/11450146/14537979/88864250-0247-11e6-951b-aa1694fc1302.png)

**Comment by Sytten** [comment]
Thats interesting, I will that a a look at it

**Comment by iliyang** [comment]
I'm having the same issue. Thanks for looking into it!

**Comment by Sytten** [comment]
@nevercast That is something that should be handle eventually...

**Comment by nevercast** [comment]
Yes this gets me often too. We will fix this.

**Comment by Sytten** [comment]
Should we put the delete in the context menu or just forget about that context menu. I actually find it quite useless and I would personally prefer something like:
Delete
Copy
Paste

**Comment by nevercast** [comment]
I actually somewhat agree with you. Removing the context menu would also save me having to resolve the popup location on OSX ;)

@Aluxian Is the context-menu strongly desired by the user base?

**Comment by Aluxian** [comment]
I agree on finding a better alternative.

I don't think so. In fact, many users don't even know or think about it, so those features remain hidden from them.

--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Wed, May 18, 2016 at 10:48 PM, Josh Lloyd < notifications@github.com [notifications@github.com] > wrote:
I actually somewhat agree with you. Removing the context menu would also save me having to resolve the popup location on OSX ;)

@Aluxian [https://github.com/Aluxian] Is the context-menu strongly desired by the user base?

**Comment by nevercast** [comment]
@Sytten What do you think about removing the context menu for the next release and then adding it back maybe in the future once we've found a better solution? I guess we still want Copy/Paste functionality. I don't know if we have Paste at the moment, but Copy already checks for a selection of text so that won't be an issue.

If there is no items on the menu, we wont show it.
Thoughts?

**Comment by nevercast** [comment]
We can check if the Delete menu is present with `body div.uiContextualLayerPositioner.uiLayer` selector. We do have to delay the handler in menus.js for 100ms though because React takes some time to resolve.

But I think for now it's maybe better to get rid of the context menu. Do we keep the native nwjs one or hide that too?

**Comment by Aluxian** [comment]
Hmm so there are 3 context menus? The one from Messenger, the one we implemented, and the nwjs default? I'd say we should keep just the one from Messenger.

**Comment by Sytten** [comment]
Hey, sry didn't have time to replay faster.
Yes I agree we remove the current context menu and we find a better solution for the next releases.
Copy and Paste works with shortcuts, but I like to have them also in a context menu (not that necessary)...
