### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by Sytten** [Aluxian/Messenger-for-Desktop#415]
NPM complains about a deprecated graceful-fs dependency.

**Comment by nevercast** [comment]
Doesn't matter until we hit node.js >= 7.0
Here is the tree that is using graceful-fs < 4.x

```
+-- gulp@3.9.1
| +-- vinyl-fs@0.3.14
|   +-- glob-watcher@0.0.6
|   | `-- gaze@0.5.2
|   |   `-- globule@0.1.0
|   |     `-- glob@3.1.21
|   |       `-- graceful-fs@1.2.3
|   `-- graceful-fs@3.0.8
`-- nw-builder@2.2.0 (git://github.com/nevercast/nw-builder.git#mfd)
  +-- decompress-zip@0.0.8
  | `-- graceful-fs@3.0.8
  +-- graceful-ncp@2.0.0
  | `-- graceful-fs@3.0.8
  `-- update-notifier@0.1.10
    `-- configstore@0.3.2
      `-- graceful-fs@3.0.8
```

I can probably update nw-builder to use version 4. I cannot update glob to use a version higher than `1.2.3`.

For now, this is going to be Backlogged almost indefinitely because someone will fix it before we do, keeping it open for occasional checking though.

**Comment by Aluxian** [comment]
I agree, it's not a big deal and not worth focusing on for now.


--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Tue, May 17, 2016 at 6:51 AM, Josh Lloyd < notifications@github.com [notifications@github.com] > wrote:
Doesn't matter until we hit node.js >= 7.0
Here is the tree that is using graceful-fs < 4.x

+-- gulp@3.9.1
| +-- vinyl-fs@0.3.14
|   +-- glob-watcher@0.0.6
|   | `-- gaze@0.5.2
|   |   `-- globule@0.1.0
|   |     `-- glob@3.1.21
|   |       `-- graceful-fs@1.2.3
|   `-- graceful-fs@3.0.8
`-- nw-builder@2.2.0 (git://github.com/nevercast/nw-builder.git#mfd)
  +-- decompress-zip@0.0.8
  | `-- graceful-fs@3.0.8
  +-- graceful-ncp@2.0.0
  | `-- graceful-fs@3.0.8
  `-- update-notifier@0.1.10
    `-- configstore@0.3.2
      `-- graceful-fs@3.0.8


I can probably update nw-builder to use version 4. I cannot update glob to use a version higher than 1.2.3 .

For now, this is going to be Backlogged almost indefinitely because someone will fix it before we do, keeping it open for occasional checking though.

**Comment by Sytten** [comment]
Good issue done

**Comment by nevercast** [comment]
I just ask that we keep this open, as it's not actually fixed, although it's not our issue we should keep an eye on it incase it causes an issue in the future.

**Comment by Sytten** [comment]
Ok ok perfect
